# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "custom"

replicaCount: 1

service:
  port: 4526

volumes:
  - name: custom-tmp-dir
    emptyDir: {}

containers:
  - name: custom
    image: cyberdojo/custom
    tag: ""
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: custom-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
    livenessProbe:
       path: /sha
       port: 4526
    readinessProbe:
       path: /ready?
       port: 4526

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
