# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "languages"

replicaCount: 1

service:
  port: 4524

volumes:
  - name: languages-tmp-dir
    emptyDir: {}

containers:
  - name: languages
    image: cyberdojo/languages-all
    tag: ""
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: languages-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
    livenessProbe:
       path: /sha
       port: 4524
    readinessProbe:
       path: /ready?
       port: 4524

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
